version: '2.1'

services:
  kafka-broker:
    image: apache/kafka:latest
    hostname: kafka-broker
    container_name: kafka-broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - service-network

  cli-tool-consumer:
    container_name: cli-tool-consumer
    image: developkisa/111513705-kafka-cli-tool:latest
    command: consume --topic hello_topic --kafka ${KAFKA_IP:-localhost}:${KAFKA_PORT:-9092}
    depends_on:
      - kafka-broker
    env_file:
      - .env
    networks:
      - service-network

  cli-tool-producer:
    container_name: cli-tool-producer
    image: developkisa/111513705-kafka-cli-tool:latest
    command: produce --message "Hello World!" --topic hello_topic --kafka ${KAFKA_IP:-localhost}:${KAFKA_PORT:-9092}
    depends_on:
      - kafka-broker
    env_file:
      - .env
    networks:
      - service-network

networks:
    service-network:
        name: service-network